% File src/library/XGR/vignettes/XGR.Rnw
% Part of the R package, http://www.R-project.org
% Distributed under GPL 2 or later

%\VignetteIndexEntry{XGR User Manual}
%\VignettePackage{XGR}
%\VignetteKeywords{Bioinformatics}
%\VignetteDepends{XGR}


\documentclass[a4paper]{article}

\usepackage[authoryear,round]{natbib}
\usepackage{amsmath}

\usepackage{color}
\definecolor{darkblue}{rgb}{0.0,0.0,0.75}
\definecolor{darkred}{rgb}{0.75,0.0,0.0}
\definecolor{lightyellow}{rgb}{1,1,0.85}
\usepackage[%
baseurl={http://www.bioconductor.org},%
pdftitle={XGR Manual},%
pdfauthor={Hai Fang},%
pdfkeywords={Bioinformatics},%
pagebackref,bookmarks,%
colorlinks,%
linkcolor=darkred,%
citecolor=darkblue,%
raiselinks,plainpages,pdftex]{hyperref}

\SweaveOpts{keep.source=TRUE,eps=FALSE,include=FALSE} 

\newcommand{\Rfunction}[1]{{\texttt{#1}}}
\newcommand{\Robject}[1]{{\texttt{#1}}}
\newcommand{\Rpackage}[1]{\textit{#1}}
\newcommand{\Rclass}[1]{{\textit{#1}}}
\newcommand{\Rfile}[1]{{\texttt{#1}}}

\newcommand{\Rtitle}[1]{{\texttt{#1}}}

\newcommand{\test}[1]{%
    \textcolor{red}{#1}
    \textit{#1}
}

\newcommand{\myincfig}[4]{%
  \begin{figure}[!ht]
    \begin{center}
      \includegraphics[width=#2]{#1}
      \caption[#3]{\texttt{\label{#1}#3}. \label{#1}#4}
    \end{center}
  \end{figure}
}

%------------------------------------------------------------
\pagecolor{white}
\begin{document}
\SweaveOpts{concordance=TRUE}


\title{\Rpackage{XGR}: an R package for deciphering genes and SNPs identified from GWAS and eQTLs}
\date{}
\maketitle
%------------------------------------------------------------

%\setlength{\parskip}{0pt}
\vspace{12pt}
\begin{abstract}
\noindent We introduce an R package called \Rpackage{XGR}\footnote{\url{https://github.com/hfang-bristol/XGR}}. ... Taking a list of user-input genes (or SNPs), the package 'XGR' is able to identify the underlying knowledge enriched within them, and to predict the semantic similarity between them. The package supports a wide range of ontologies (including functions, pathways, diseases and phenotypes in both human and mouse) for users to choose and thus to produce enriched knowledge and semantic similarity of their own interest.
\end{abstract}

\newpage
\tableofcontents
\listoftables
\listoffigures
\newpage


%------------------------------------------------------------
\section{Introduction}
\label{sec:intro}
%------------------------------------------------------------

\newpage
%------------------------------------------------------------
\section{Installation and Citation}
\label{sec:inst}
%------------------------------------------------------------

\newpage
%------------------------------------------------------------
\section{Quick Overview}\label{sec:overview}
%------------------------------------------------------------

\newpage
%------------------------------------------------------------
\section{Main Functionality}\label{sec:func}
%------------------------------------------------------------

\newpage
%------------------------------------------------------------
\section{Applications to Real Cases}\label{sec:case}
%------------------------------------------------------------

\newpage
%------------------------------------------------------------
\section{Session Information}
\label{sec:ses}
%------------------------------------------------------------
All of the output in this vignette was produced under the following conditions:

<<sessinfo>>=
sessionInfo()
@

\end{document}
